# Generated by Django 5.1.5 on 2025-01-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название блюда', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Описание блюда', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена блюда', max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
