# Generated by Django 5.1.5 on 2025-01-24 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='menu.dish', verbose_name='Список блюд в заказе'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('done', 'готово'), ('paid', 'оплачено'), ('pending', 'в ожидании')], default='в ожидании', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер стола'),
        ),
    ]
